/**
 * Quick-pick brainstorm prompts. ~1000 themes covering sports, cities,
 * passions, food, music, nature, animals, mythology, and much more.
 * 12 are randomly shown on the Brainstorm page per visit.
 */

export interface QuickPick {
  label: string;
  prompt: string;
}

// Helper to build entries concisely — label becomes prompt with keyword list
const t = (label: string, keywords: string): QuickPick => ({
  label,
  prompt: `${label.toLowerCase()} — ${keywords}`,
});

export const QUICK_PICK_POOL: QuickPick[] = [
  // ========== SPORTS ==========
  t('Baseball', 'leather mitt, wooden bat, pitcher mound, diamond, stadium lights, vintage Americana'),
  t('Football', 'gridiron, pigskin, helmet silhouette, tackling, Friday night lights'),
  t('Basketball', 'hoop, backboard, streetball, asphalt court, bouncing rhythm'),
  t('Soccer', 'football pitch, checkered ball, stadium tifos, global game'),
  t('Tennis', 'clay court, racquet strings, chalk lines, grand slam'),
  t('Golf', 'fairway, flag pin, tee off, country club elegance'),
  t('Ice Hockey', 'skates, slap shot, rink, crossed sticks'),
  t('Boxing', 'gloves, heavy bag, corner stool, championship belt'),
  t('MMA', 'octagon cage, fight night, submission grappling'),
  t('Karate', 'dojo, gi belt, bonsai tree, focus stance'),
  t('Surfing', 'breaking wave, board fins, tropical sunset, tube ride'),
  t('Skateboarding', 'half pipe, ollie, grip tape, urban decks'),
  t('Snowboarding', 'fresh powder, mountain cornice, carving tracks'),
  t('Skiing', 'alpine slopes, ski lift, moguls, winter chalet'),
  t('Cycling', 'peloton, gear cog, mountain switchback'),
  t('Running', 'track lanes, finish tape, marathon miles'),
  t('Rugby', 'scrum, rugby ball, muddy pitch'),
  t('Cricket', 'wickets, willow bat, oval pitch'),
  t('Volleyball', 'beach sand, spike, net silhouette'),
  t('Swimming', 'lap lane, pool tiles, breaststroke'),
  t('Rowing', 'crew shell, oar blades, misty river'),
  t('Sailing', 'mainsail, regatta, compass heading'),
  t('Archery', 'drawn bow, target rings, fletching feathers'),
  t('Bowling', 'pin strike, retro lanes, disco ball'),
  t('Billiards', 'felt table, cue ball, break rack'),
  t('Fencing', 'foil blades, en garde, mesh mask'),
  t('Wrestling', 'singlet, mat, takedown'),
  t('Sumo', 'mawashi, dohyō ring, ritual stance'),
  t('Horseback Riding', 'saddle, reins, galloping silhouette'),
  t('Equestrian', 'show jumping, dressage, polo pony'),
  t('Rodeo', 'bucking bronco, lasso, cowboy hat'),
  t('Bull Riding', 'bull horns, eight seconds, arena dust'),
  t('Auto Racing', 'checkered flag, racing stripe, burnout smoke'),
  t('Formula 1', 'race livery, apex turn, podium'),
  t('NASCAR', 'oval track, stock cars, pit stop'),
  t('Motocross', 'dirt bike, berm, whip trick'),
  t('BMX', 'dirt jumps, handlebar, freestyle'),
  t('Rock Climbing', 'chalk bag, crimpers, granite wall'),
  t('Bouldering', 'crash pad, dynamic move, indoor gym'),
  t('Mountaineering', 'ice axe, summit push, prayer flags'),
  t('Parkour', 'rooftop leap, urban flow, vault'),
  t('Skydiving', 'free fall, parachute bloom, altimeter'),
  t('Paragliding', 'wing glider, thermal lift, valley view'),
  t('Hang Gliding', 'frame wing, cliff launch'),
  t('Scuba Diving', 'oxygen tank, coral forest, schooling fish'),
  t('Freediving', 'breath hold, blue depth, weighted descent'),
  t('Spearfishing', 'polespear, reef hunt, breath training'),
  t('Kayaking', 'whitewater, paddle blade, river bend'),
  t('Canoeing', 'birchbark hull, glacial lake, portage'),
  t('Fishing', 'fly rod, trout stream, tackle box'),
  t('Ice Fishing', 'auger hole, frozen lake, tip-up flag'),
  t('Fly Fishing', 'dry fly, riffles, waders'),
  t('Deep Sea Fishing', 'marlin, trolling, blue water'),
  t('Hunting', 'camo blind, scope crosshair, antler rack'),
  t('Falconry', 'gauntlet glove, raptor hood, bells'),
  t('Dodgeball', 'gym rubber, dodge weave'),
  t('Lacrosse', 'webbed stick, goalie cage'),
  t('Polo', 'mallet swing, pony gallop, chukker'),
  t('Sailing Regatta', 'spinnaker sail, tacking line, harbor buoys'),
  t('Cheerleading', 'pom-poms, pyramid stunt, school spirit'),
  t('Gymnastics', 'balance beam, uneven bars, chalk grip'),
  t('Weightlifting', 'barbell plates, clean and jerk, gym iron'),
  t('Powerlifting', 'squat rack, deadlift, chalked hands'),
  t('Crossfit', 'kettlebell, rope climb, WOD chalkboard'),
  t('Yoga', 'lotus pose, sun salutation, mat in forest'),
  t('Pilates', 'reformer, core control, breath flow'),
  t('Dance', 'barre, pirouette, stage light'),
  t('Ballet', 'pointe shoes, tutu, studio mirror'),
  t('Breakdancing', 'cardboard stage, power moves, boombox'),
  t('Tap Dance', 'metal heel, rhythm, vaudeville'),
  t('Martial Arts', 'black belt, kata, dojo altar'),
  t('Kung Fu', 'tiger stance, crane form, Shaolin temple'),
  t('Muay Thai', 'knee strike, Thai pad, clinch'),
  t('Jiu-Jitsu', 'gi sleeve, rolling ground, submission'),
  t('Capoeira', 'berimbau, roda circle, acrobatic kick'),

  // ========== US CITIES ==========
  t('New York City', 'skyline, yellow cab, subway tiles, Empire State'),
  t('Brooklyn', 'brownstones, street corner, bridge cables'),
  t('Manhattan', 'grid streets, Central Park, neon Times Square'),
  t('Los Angeles', 'palm trees, Hollywood sign, sunset boulevard'),
  t('Hollywood', 'film reel, star walk, klieg lights'),
  t('Venice Beach', 'boardwalk, muscle beach, surf culture'),
  t('Chicago', 'deep dish, Bean sculpture, L train, lakefront'),
  t('Miami', 'art deco hotels, pastel flamingos, South Beach neon'),
  t('Seattle', 'Space Needle, coffee cup, misty evergreens, grunge'),
  t('San Francisco', 'Golden Gate, cable cars, fog rolling, Victorian row'),
  t('Boston', 'cobblestone, Freedom Trail, harbor tea'),
  t('Austin', 'live music, food trucks, armadillo, bats under bridge'),
  t('Nashville', 'honky tonk, guitar neck, Music Row'),
  t('Memphis', 'blues club, Beale Street, Elvis silhouette'),
  t('Portland', 'rose garden, bridge city, quirky aesthetic'),
  t('Denver', 'mile high, mountain skyline, brewery'),
  t('Las Vegas', 'neon strip, slot machines, desert mirage'),
  t('New Orleans', 'wrought iron balconies, jazz horn, beignet powdered sugar'),
  t('Atlanta', 'peach, Olympic torch, Sweet Auburn'),
  t('Savannah', 'Spanish moss, historic squares, ghost stories'),
  t('Charleston', 'pastel row houses, wrought gates, harbor'),
  t('Dallas', 'cattle horn, stockyards, lone star'),
  t('Houston', 'space center, rocket, ship channel'),
  t('San Antonio', 'Alamo, river walk, mission bell'),
  t('Phoenix', 'saguaro silhouette, sun circle, desert heat'),
  t('Sedona', 'red rock, vortex, pine juniper'),
  t('Salt Lake City', 'temple spires, Bonneville flats, ski mountain'),
  t('Honolulu', 'lei, Diamond Head, aloha sunrise'),
  t('Maui', 'road to Hana, sea turtle, volcano crater'),
  t('Anchorage', 'aurora, grizzly, Denali'),
  t('Washington DC', 'monuments, cherry blossoms, marble columns'),
  t('Philadelphia', 'liberty bell, cheesesteak, rocky steps'),
  t('Baltimore', 'inner harbor, row houses, old glory'),
  t('Detroit', 'motor city, vinyl records, industrial grit'),
  t('Pittsburgh', 'three rivers, steel bridges, incline'),
  t('Cleveland', 'rock hall, Lake Erie, factory steam'),
  t('Minneapolis', 'twin cities, ten thousand lakes, grain mill'),
  t('Kansas City', 'fountains, jazz clubs, BBQ smoke'),

  // ========== WORLD CITIES ==========
  t('Tokyo', 'neon alleys, shibuya crossing, bullet train, cherry blossom'),
  t('Shibuya', 'scramble crossing, neon katakana, fashion tribes'),
  t('Kyoto', 'bamboo grove, torii gate, geisha district'),
  t('Osaka', 'takoyaki, glico man, dotonbori'),
  t('Hiroshima', 'paper cranes, peace park, miyajima'),
  t('Sapporo', 'snow festival, ramen, beer garden'),
  t('Okinawa', 'turquoise reef, shisa lions, ryukyu'),
  t('Seoul', 'palace gates, k-pop, bibimbap'),
  t('Busan', 'coastal cliffs, temple by sea'),
  t('Shanghai', 'bund waterfront, Pearl Tower, nightlife skyline'),
  t('Hong Kong', 'junk boat, skyscrapers, neon Cantonese signs'),
  t('Beijing', 'Forbidden City, hutong alleys, Great Wall'),
  t('Taipei', 'night market, 101 tower, scooter swarm'),
  t('Bangkok', 'tuk tuk, golden temple, floating market'),
  t('Chiang Mai', 'lanterns, mountain temples, elephants'),
  t('Phuket', 'longtail boat, limestone karst'),
  t('Bali', 'rice terraces, temple offerings, surf break'),
  t('Singapore', 'marina bay, supertrees, hawker stalls'),
  t('Kuala Lumpur', 'petronas towers, batu caves'),
  t('Hanoi', 'old quarter, pho steam, lotus pond'),
  t('Ho Chi Minh', 'motorbike sea, french colonial, banh mi'),
  t('Siem Reap', 'angkor wat, jungle temples'),
  t('Manila', 'jeepney, rice terraces, volcano lake'),
  t('Bali Ubud', 'monkey forest, yoga retreats, rice paddies'),
  t('Mumbai', 'bollywood, gateway of india, tiffin carriers'),
  t('Delhi', 'spice market, red fort, auto rickshaw'),
  t('Jaipur', 'pink city, palace, elephant festival'),
  t('Varanasi', 'ghats, Ganges aarti, holy fires'),
  t('Goa', 'palm beach, Portuguese churches, trance'),
  t('Kathmandu', 'prayer wheels, Himalayan vista, stupa eyes'),
  t('Dubai', 'burj khalifa, desert falcon, gold souk'),
  t('Abu Dhabi', 'grand mosque domes, luxury dunes'),
  t('Istanbul', 'bosphorus ferry, blue mosque, bazaar'),
  t('Cappadocia', 'balloon sky, fairy chimneys, cave hotels'),
  t('Cairo', 'pyramid silhouette, nile felucca, bazaar'),
  t('Marrakech', 'souk lanterns, riad courtyard, atlas mountains'),
  t('Fez', 'tannery, medina alleys, blue tilework'),
  t('Cape Town', 'table mountain, vineyards, ocean cliff'),
  t('Nairobi', 'safari gateway, acacia silhouette'),
  t('Lagos', 'afrobeats, lagos nightlife, market'),
  t('Zanzibar', 'stone town doors, dhow boat, spice'),
  t('Moscow', 'saint basil domes, red square, kremlin'),
  t('Saint Petersburg', 'winter palace, canals, ballet'),
  t('Prague', 'charles bridge, astronomical clock, spires'),
  t('Vienna', 'opera house, sachertorte, imperial waltz'),
  t('Budapest', 'thermal baths, parliament spire, danube'),
  t('Berlin', 'graffiti wall, brandenburg gate, club nights'),
  t('Munich', 'beer hall, alpine foothills, oktoberfest'),
  t('Amsterdam', 'canal house, bicycles, tulip fields'),
  t('Brussels', 'grand place, art nouveau, chocolate'),
  t('Copenhagen', 'little mermaid, nyhavn harbor, hygge'),
  t('Stockholm', 'archipelago, gamla stan, fika'),
  t('Oslo', 'fjord, viking ship, opera house'),
  t('Helsinki', 'design district, sauna, baltic cold'),
  t('Reykjavik', 'northern lights, geothermal, volcanic rock'),
  t('Rome', 'colosseum, trevi fountain, cobbled alleys'),
  t('Venice', 'gondola, grand canal, mask of carnival'),
  t('Florence', 'duomo, arno river, renaissance sculpture'),
  t('Milan', 'fashion runway, galleria arcade'),
  t('Naples', 'vesuvius, pizza kitchen, vespa streets'),
  t('Sicily', 'mount etna, lemon groves, baroque town'),
  t('Amalfi Coast', 'cliff houses, lemon trees, turquoise bays'),
  t('Madrid', 'tapas bar, royal palace, flamenco'),
  t('Barcelona', 'gaudi spires, las ramblas, beach tapas'),
  t('Seville', 'flamenco, orange trees, moorish palace'),
  t('Ibiza', 'white beach, sunset DJ, club island'),
  t('Lisbon', 'yellow tram, tile facades, fado'),
  t('Porto', 'port wine, azulejo, douro river'),
  t('Paris', 'eiffel silhouette, sidewalk cafe, seine boat'),
  t('London', 'double decker, big ben, misty thames'),
  t('Dublin', 'pub nights, literary quarter, green hills'),
  t('Edinburgh', 'royal mile, castle rock, highland thistle'),
  t('Sydney', 'opera sails, harbor bridge, bondi surfer'),
  t('Melbourne', 'laneway graffiti, coffee culture, trams'),
  t('Auckland', 'city of sails, volcano islands'),
  t('Queenstown', 'bungee leap, alpine lake, adventure capital'),
  t('Toronto', 'cn tower, islands, distillery district'),
  t('Montreal', 'old town cobbles, notre-dame, jazz fest'),
  t('Vancouver', 'stanley park, harbor float planes, mountains'),
  t('Mexico City', 'zocalo, frida kahlo, lucha libre'),
  t('Oaxaca', 'mezcal, alebrije creatures, dia de muertos'),
  t('Tulum', 'mayan ruins, cenote, jungle beach'),
  t('Havana', 'classic cars, malecón, cigar smoke'),
  t('Rio de Janeiro', 'christ statue, copacabana, favela colors'),
  t('São Paulo', 'graffiti, skyline, boteco'),
  t('Buenos Aires', 'tango, la boca houses, café porteño'),
  t('Patagonia', 'glacial peaks, guanaco, windswept plains'),
  t('Lima', 'ceviche, pacific cliffs, pre-inca'),
  t('Cusco', 'terracotta roofs, andean textile, llama'),
  t('Machu Picchu', 'stone terraces, andean mist'),
  t('Santiago', 'andes backdrop, vineyard, bellavista'),

  // ========== PASSIONS & HOBBIES ==========
  t('Boating', 'marina, bowline knot, sunset cruise, wake trail'),
  t('Yachting', 'teak deck, spinnaker, mediterranean cruise'),
  t('Sailing Life', 'compass, jibing line, horizon'),
  t('Camping', 'campfire, pine needles, star gazing tent'),
  t('Backpacking', 'trail blaze, pack weight, ridge vista'),
  t('Hiking', 'switchback trail, alpine pass, boot prints'),
  t('Glamping', 'safari tent, outdoor lounge, luxury woods'),
  t('Van Life', 'sprinter van, roof rack, nomad stove'),
  t('Overlanding', 'rooftop tent, desert wash, winch gear'),
  t('RV Life', 'airstream, highway sunset, KOA'),
  t('Birdwatching', 'binoculars, field guide, feather detail'),
  t('Stargazing', 'telescope, milky way band, observatory'),
  t('Astronomy', 'constellation map, nebula, cosmic'),
  t('Astrophotography', 'star trail, long exposure, deep space'),
  t('Photography', 'lens, aperture, darkroom, film grain'),
  t('Film Photography', '35mm grain, dust spots, analog soul'),
  t('Street Photography', 'candid moment, urban light, silver gelatin'),
  t('Model Building', 'x-acto knife, glue cement, miniature detail'),
  t('Model Trains', 'ho scale, depot, locomotive'),
  t('Woodworking', 'chisel, dovetail joint, sawdust'),
  t('Carpentry', 'tape measure, framing square, shavings'),
  t('Wood Carving', 'whittled knife, relief sculpture'),
  t('Blacksmithing', 'forge flame, anvil, hammer spark'),
  t('Bladesmithing', 'damascus steel, quench oil, layered pattern'),
  t('Jewelry Making', 'wire wrap, bezel setting, gemstone'),
  t('Leatherworking', 'awl, saddle stitch, oxblood wax'),
  t('Bookbinding', 'coptic stitch, marbled paper'),
  t('Origami', 'crane fold, paper geometry'),
  t('Calligraphy', 'brush stroke, ink well, flourished letter'),
  t('Lettering', 'hand lettered, flourish, typography study'),
  t('Watercolor', 'wet on wet, pigment bloom, loose brush'),
  t('Sketching', 'graphite line, quick gesture, sketchbook'),
  t('Printmaking', 'linocut, brayer roller, registration'),
  t('Pottery', 'wheel throw, slip glaze, kiln'),
  t('Ceramics', 'raku crackle, porcelain, wabi sabi'),
  t('Sculpture', 'chisel stone, lost wax, marble dust'),
  t('Stained Glass', 'lead came, fractured light, cathedral window'),
  t('Glass Blowing', 'molten gather, punty rod, furnace'),
  t('Candle Making', 'wax pour, wick trim, apothecary jar'),
  t('Perfumery', 'accord, base note, crystal bottle'),
  t('Herbalism', 'tincture, dried bouquet, mortar pestle'),
  t('Foraging', 'mushroom basket, wildcraft, field guide'),
  t('Gardening', 'trowel, heirloom seed, compost bin'),
  t('Beekeeping', 'hive frame, smoker, honeycomb'),
  t('Homesteading', 'root cellar, chicken coop, cast iron'),
  t('Canning', 'mason jar, boiling bath, preserves'),
  t('Fermenting', 'sourdough starter, crock jar, bubbles'),
  t('Home Brewing', 'carboy, hop cones, yeast foam'),
  t('Wine Making', 'barrel cellar, grape press, vintage label'),
  t('Cheese Making', 'curd cut, aging cave, rind culture'),
  t('Bread Baking', 'sourdough loaf, dutch oven, flour bench'),
  t('Cooking', 'mise en place, cast iron pan, fresh herbs'),
  t('Baking', 'kitchen scale, oven glow, laminated dough'),
  t('Grilling', 'flame kiss, grill marks, charcoal smoke'),
  t('Smoking Meat', 'pitmaster, brisket bark, low and slow'),
  t('Mixology', 'julep cup, bitters dash, ice craft'),
  t('Coffee Roasting', 'green bean, drum roaster, first crack'),
  t('Tea Ceremony', 'chawan bowl, whisk, tatami'),
  t('Chess', 'king and pawn, wooden board, clock'),
  t('Poker', 'felt table, chip stack, river card'),
  t('Board Games', 'meeple, dice tower, hex map'),
  t('Video Games', 'pixel hero, controller, coop couch'),
  t('Retro Gaming', 'cartridge, CRT glow, arcade stick'),
  t('Tabletop RPG', 'd20, character sheet, dungeon map'),
  t('Magic Tricks', 'top hat, cards fanned, rabbit'),
  t('Juggling', 'clubs arc, cascade pattern, circus'),

  // ========== FOOD & DRINK ==========
  t('Coffee Culture', 'espresso pull, latte heart, cup ring'),
  t('Espresso', 'portafilter, crema, steam wand'),
  t('Pour Over', 'gooseneck kettle, chemex, bloom'),
  t('Tea', 'loose leaf, teapot, steam rise'),
  t('Matcha', 'bamboo whisk, green froth, chasen'),
  t('Bubble Tea', 'tapioca pearl, wide straw, milk tea'),
  t('Whiskey', 'oak barrel, rocks glass, warm glow'),
  t('Bourbon', 'kentucky still, charred barrel'),
  t('Scotch', 'highland peat, glencairn, tartan'),
  t('Tequila', 'agave field, lime salt, shot'),
  t('Mezcal', 'smoky agave, clay jug, worm'),
  t('Rum', 'pirate cove, molasses, tiki mug'),
  t('Wine', 'grape cluster, decanter, tasting'),
  t('Craft Beer', 'hop cone, tap handle, amber glow'),
  t('Cocktails', 'shaker tin, coupe glass, garnish twist'),
  t('Sushi', 'nigiri, soy drop, knife precision'),
  t('Ramen', 'broth swirl, noodle nest, chopsticks'),
  t('Tacos', 'corn tortilla, salsa verde, limón'),
  t('Pizza', 'pepperoni, bubble crust, slice drip'),
  t('Pasta', 'hand rolled, semolina, fork twirl'),
  t('BBQ', 'rack of ribs, wood smoke, pitmaster'),
  t('Burgers', 'smash patty, sesame bun, cheese drip'),
  t('Steakhouse', 'porterhouse, red wine, medium rare'),
  t('Oysters', 'raw bar, mignonette, shell'),
  t('Curry', 'spice mortar, coconut base, naan'),
  t('Dim Sum', 'bamboo basket, dumpling pleat, tea cart'),
  t('Pho', 'bone broth, basil leaf, beef slices'),
  t('Banh Mi', 'baguette, pickled carrot, cilantro'),
  t('Mediterranean', 'olive branch, feta crumble, hummus swirl'),
  t('Middle Eastern', 'shawarma, saffron, tiled mosaic'),
  t('Korean Food', 'kimchi, bulgogi, banchan spread'),
  t('Thai Food', 'pad thai, lime, chili crunch'),
  t('Mexican Food', 'salsa molcajete, cilantro, chile'),
  t('Italian Trattoria', 'checked cloth, fiasco chianti, nonna'),
  t('French Patisserie', 'éclair, macaron tower, gold leaf'),
  t('Indian Spice', 'turmeric, cardamom pod, garam masala'),
  t('Caribbean', 'jerk spice, rum drink, sun sea'),
  t('Cajun Creole', 'crawfish boil, andouille, swamp'),
  t('Southern Comfort', 'fried chicken, biscuit, sweet tea'),
  t('Deli', 'pastrami, rye, pickle spear'),
  t('Diner', 'chrome counter, milkshake, pie case'),
  t('Food Truck', 'street window, order slip, neon'),
  t('Farm to Table', 'heirloom, root vegetable, chef garden'),
  t('Gelato', 'italian scoop, piadina, cherry ribbon'),
  t('Ice Cream', 'soft serve, waffle cone, sprinkles'),
  t('Donuts', 'glazed ring, maple bar, old fashioned'),
  t('Bagels', 'everything seed, hand rolled, lox'),
  t('Chocolate', 'cacao pod, truffle, bar snap'),
  t('Pastries', 'croissant layers, puff pastry'),

  // ========== MUSIC ==========
  t('Jazz', 'saxophone, smoky club, snare brush'),
  t('Blues', 'delta guitar, harmonica wail, crossroads'),
  t('Rock & Roll', 'electric guitar, leather jacket, amp stack'),
  t('Punk Rock', 'safety pin, mohawk, DIY zine'),
  t('Heavy Metal', 'flaming skull, double kick, denim vest'),
  t('Death Metal', 'corpse paint, blast beat, darkness'),
  t('Grunge', 'flannel, distorted chord, northwest rain'),
  t('Hip Hop', 'boom box, turntable, spray can'),
  t('Old School Hip Hop', 'graffiti tag, breakdance, fat laces'),
  t('R&B', 'soul mic, velvet mood'),
  t('Soul', 'motown horn, tambourine, finger snap'),
  t('Funk', 'wah wah, bell bottom, groove bass'),
  t('Disco', 'glitter ball, dance floor, roller skate'),
  t('Techno', 'drum machine, detroit warehouse, strobe'),
  t('House Music', 'four on floor, piano chord, dance cult'),
  t('EDM', 'festival lights, bass drop, main stage'),
  t('Dubstep', 'wobble bass, gritty drops'),
  t('Reggae', 'dub horn, rastafarian colors, island'),
  t('Country', 'acoustic campfire, highway radio, honky tonk'),
  t('Bluegrass', 'banjo roll, fiddle, mountain porch'),
  t('Folk', 'fingerpicked guitar, vinyl warmth'),
  t('Classical', 'sheet music, conductor baton, orchestra pit'),
  t('Opera', 'chandelier, aria pose, stage'),
  t('Synthwave', 'neon grid, retrofuture sun, palm'),
  t('Vaporwave', 'glitched bust, tropical marble, 80s mall'),
  t('Lo-fi', 'cassette warmth, study beats, chill vibe'),
  t('K-Pop', 'idol group, glitter stage, hangul'),
  t('Salsa', 'clave rhythm, horn section, dancefloor'),
  t('Tango', 'rose between teeth, argentine flicker'),
  t('Flamenco', 'red dress, staccato heel, guitar rasgueado'),
  t('Mariachi', 'charro suit, trumpet fanfare, guitarrón'),
  t('Afrobeat', 'lagos horn, polyrhythm, protest groove'),

  // ========== VEHICLES ==========
  t('Muscle Cars', 'chrome grille, v8 rumble, racing stripe'),
  t('Hot Rods', 'flame paint, chopped top, pinstripe'),
  t('Lowriders', 'hydraulic hop, candy paint, wire wheels'),
  t('Classic Cars', 'vintage hood ornament, patina, wood dash'),
  t('Ferrari', 'prancing horse, italian red, apex'),
  t('Porsche', 'flat six, silhouette, autobahn'),
  t('Mustang', 'galloping pony, fastback, american'),
  t('Corvette', 'crossed flags, curvy fender'),
  t('Tesla', 'minimalist EV, neon grid'),
  t('Jeep', 'seven slot grille, topless trail, rubicon'),
  t('Land Cruiser', 'safari rack, desert overland'),
  t('Pickup Trucks', 'tailgate, bed of tools, haul life'),
  t('Off-Road', 'mud tire, winch, boulder crawl'),
  t('VW Bus', 'peace sign, beach vintage, curtain window'),
  t('Airstream', 'polished aluminum, silver bullet'),
  t('Harley Davidson', 'eagle wings, chrome, open road'),
  t('Café Racer', 'rearset, clip-on bar, leather tank'),
  t('Bobber', 'stripped frame, solo seat'),
  t('Chopper', 'raked fork, long bike'),
  t('Dirt Bike', 'knobby tire, moto plate, jump berm'),
  t('Vespa', 'italian scooter, pastel, dolce vita'),
  t('Cruiser Bicycle', 'basket, bell, boardwalk'),
  t('Fixie', 'single speed, messenger bag'),
  t('BMX Bike', 'pegs, bar spin, dirt jump'),
  t('Longboard', 'downhill carve, cruiser deck'),
  t('Roller Skates', 'quad wheels, disco rink'),
  t('Sailboat', 'mast, jib sail, harbor'),
  t('Tall Ship', 'rigging, crow nest, sails full'),
  t('Pirate Ship', 'jolly roger, cannons, cutlass'),
  t('Submarine', 'periscope, hull rivets, deep dive'),
  t('Yacht', 'mega deck, champagne, aft lounge'),
  t('Speedboat', 'hull slap, wake, aquaplane'),
  t('Jet Ski', 'spray arc, shore jump'),
  t('Hot Air Balloon', 'burner flame, wicker basket, dawn drift'),
  t('Zeppelin', 'art deco airship, gondola, golden age'),
  t('Biplane', 'canvas wing, leather cap, aerobatic'),
  t('Fighter Jet', 'afterburner, canopy, carrier deck'),
  t('Helicopter', 'rotor blur, door gunner'),
  t('Rocket', 'launch plume, gantry, stars'),
  t('Space Shuttle', 'orbiter tile, robotic arm'),
  t('Drone', 'quadcopter, aerial frame, FPV'),

  // ========== NATURE ==========
  t('Redwood Forest', 'ancient giants, mossy floor, fog'),
  t('Rainforest', 'canopy layers, howler monkey, vines'),
  t('Amazon Jungle', 'river snake, jaguar, piranha'),
  t('Savanna', 'acacia silhouette, migrating herd, sunset'),
  t('Tundra', 'caribou, frozen moss, arctic sun'),
  t('Taiga', 'pine sea, aurora overhead'),
  t('Swamp', 'cypress knee, gator eyes, spanish moss'),
  t('Mangrove', 'root stilt, tidal fish'),
  t('Coral Reef', 'clownfish, anemone sway, blue lagoon'),
  t('Kelp Forest', 'sea otter, sun beams, underwater cathedral'),
  t('Volcano', 'lava river, caldera, ash cloud'),
  t('Glacier', 'blue ice crack, crevasse, carving wall'),
  t('Iceberg', 'titanic blue, polar seas'),
  t('Canyon', 'layered strata, river cut'),
  t('Grand Canyon', 'south rim, colorado river, vista'),
  t('Waterfall', 'cascade, moss curtain, rainbow mist'),
  t('Geyser', 'steam blast, mineral terrace, yellowstone'),
  t('Hot Springs', 'soaking pool, steam, iceland'),
  t('Cave', 'stalactites, headlamp, subterranean'),
  t('Cenote', 'jungle pool, light beam, limestone'),
  t('Mountain Range', 'ridgeline panorama, snowcap'),
  t('Himalayas', 'prayer flags, everest, sherpa'),
  t('Alps', 'cow bells, cable car, chalet'),
  t('Rockies', 'aspen gold, elk bugle'),
  t('Prairie', 'wheat wave, windmill, homestead'),
  t('Fjord', 'cliff wall, narrow sea, norwegian'),
  t('Cliff Coast', 'sea stack, gull, blowhole'),
  t('Atoll', 'ring of coral, lagoon turquoise'),
  t('Tropical Island', 'palm shade, hammock, crystal water'),
  t('White Sand Beach', 'powdered sand, clear shallow'),
  t('Black Sand Beach', 'volcanic grit, basalt column'),
  t('Sand Dune', 'ripple shadow, sahara, camel'),
  t('Desert', 'mirage shimmer, red rock, cactus'),
  t('Joshua Tree', 'yucca silhouette, high desert'),
  t('Saguaro', 'arm raised cactus, sonoran sunset'),
  t('Yosemite', 'half dome, waterfall cliff'),
  t('Aurora Borealis', 'green curtain, arctic night'),
  t('Meteor Shower', 'shooting stars, dark sky park'),
  t('Milky Way', 'galactic core, cosmic dust'),
  t('Sunset', 'golden hour, horizon glow'),
  t('Sunrise', 'first light, dew mist'),
  t('Storm Clouds', 'thunderhead, lightning flash'),
  t('Rainbow', 'prism arc, after rain'),

  // ========== ANIMALS ==========
  t('Lion', 'mane, savanna, pride'),
  t('Tiger', 'stripe pattern, jungle prowl'),
  t('Snow Leopard', 'mountain ghost, rosette coat'),
  t('Black Panther', 'dark jaguar, stealth'),
  t('Cheetah', 'sprint spots, tear mark'),
  t('Wolf', 'pack howl, moon silhouette'),
  t('Arctic Fox', 'white fur, snow hunter'),
  t('Red Fox', 'vulpine sly, bushy tail'),
  t('Bear', 'grizzly stance, salmon catch'),
  t('Polar Bear', 'ice floe, snow giant'),
  t('Panda', 'bamboo, black and white'),
  t('Koala', 'eucalyptus, sleepy grip'),
  t('Kangaroo', 'pouch joey, outback bounce'),
  t('Elephant', 'tusk majesty, herd trunk'),
  t('Giraffe', 'long neck, acacia nibble'),
  t('Zebra', 'stripe crossing, migration'),
  t('Rhino', 'horn profile, armor skin'),
  t('Hippo', 'river mouth, tusk yawn'),
  t('Gorilla', 'silverback pose, rainforest'),
  t('Chimpanzee', 'tool use, tree canopy'),
  t('Orangutan', 'forest wise, long arm'),
  t('Lemur', 'ring tail, madagascar'),
  t('Moose', 'antler span, marsh wade'),
  t('Elk', 'bugle call, autumn rut'),
  t('Bison', 'prairie thunder, shaggy shoulder'),
  t('Buffalo', 'cape herd, dust cloud'),
  t('Deer', 'white tail, forest edge'),
  t('Stag', 'royal antler, highland mist'),
  t('Mountain Goat', 'cliff leap, white beard'),
  t('Raccoon', 'bandit mask, dumpster clever'),
  t('Otter', 'river float, clam stone'),
  t('Beaver', 'dam builder, flat tail'),
  t('Seal', 'ice haul, whisker'),
  t('Sea Lion', 'barking colony, pacific rocks'),
  t('Walrus', 'tusk beard, ice floe'),
  t('Dolphin', 'bow wave, echolocation arc'),
  t('Orca', 'killer whale, pod hunt'),
  t('Blue Whale', 'leviathan, fluke breach'),
  t('Humpback Whale', 'song migration, tail slap'),
  t('Narwhal', 'unicorn tusk, arctic myth'),
  t('Shark', 'dorsal fin, apex predator'),
  t('Great White', 'toothy grin, open ocean'),
  t('Hammerhead', 'wide head, schooling'),
  t('Octopus', 'tentacle curl, ink cloud'),
  t('Squid', 'giant kraken, deep hunter'),
  t('Jellyfish', 'pulsing bell, tendril'),
  t('Manta Ray', 'wingspan glide, plankton'),
  t('Sea Turtle', 'shell pattern, ancient mariner'),
  t('Crocodile', 'prehistoric jaw, water ambush'),
  t('Komodo Dragon', 'forked tongue, indonesian lizard'),
  t('Iguana', 'spike crest, tropical sun'),
  t('Chameleon', 'color shift, swivel eye'),
  t('Gecko', 'pad toe, nocturnal climb'),
  t('Axolotl', 'pink frill, regeneration'),
  t('Frog', 'lily pad, vocal sac'),
  t('Poison Dart Frog', 'neon warning, jungle floor'),
  t('Bald Eagle', 'white head, talon clutch'),
  t('Golden Eagle', 'soar thermal, apex bird'),
  t('Hawk', 'screech cry, perched eye'),
  t('Falcon', 'stoop dive, hooded'),
  t('Owl', 'silent wing, moon face'),
  t('Peacock', 'eye feather fan, ostentation'),
  t('Flamingo', 'pink leg, shrimp feed'),
  t('Parrot', 'macaw color, rainforest squawk'),
  t('Hummingbird', 'wing blur, nectar pause'),
  t('Swan', 'neck curve, serene glide'),
  t('Raven', 'black feather, trickster'),
  t('Crow', 'clever bird, murder flock'),
  t('Penguin', 'tuxedo waddle, antarctic'),
  t('Albatross', 'wide glide, southern ocean'),
  t('Scorpion', 'tail sting, desert armor'),
  t('Tarantula', 'hairy leg, burrow'),
  t('Beetle', 'iridescent shell, stag horn'),
  t('Butterfly', 'wing symmetry, metamorphosis'),
  t('Monarch Butterfly', 'orange migration, milkweed'),
  t('Dragonfly', 'wing stained glass, pond skim'),
  t('Moth', 'lamp attraction, feathery antenna'),
  t('Luna Moth', 'green wings, rare beauty'),
  t('Honeybee', 'hive geometry, pollen sack'),
  t('Praying Mantis', 'folded arms, patient hunter'),
  t('Snake', 'coil, scaly skin, forked tongue'),
  t('Cobra', 'hood flare, swaying charm'),
  t('Python', 'jungle squeeze, patterned scales'),
  t('Rattlesnake', 'desert warning, coiled'),

  // ========== MYTHOLOGY & FOLKLORE ==========
  t('Greek Mythology', 'olympian gods, laurel wreath, amphora'),
  t('Zeus', 'thunderbolt, cloud throne'),
  t('Athena', 'owl wisdom, aegis shield'),
  t('Poseidon', 'trident, sea horse'),
  t('Medusa', 'snake hair, stone gaze'),
  t('Pegasus', 'winged horse, cloud leap'),
  t('Minotaur', 'labyrinth beast, bull head'),
  t('Norse Mythology', 'odin raven, valhalla horn, runes'),
  t('Thor', 'hammer mjolnir, lightning'),
  t('Loki', 'trickster flame'),
  t('Valkyrie', 'winged warrior, chosen slain'),
  t('Yggdrasil', 'world tree, nine realms'),
  t('Ragnarok', 'end of worlds, wolf fenrir'),
  t('Egyptian Mythology', 'ra sun disc, eye of horus'),
  t('Anubis', 'jackal head, scales of judgement'),
  t('Sphinx', 'desert riddle, pharaoh face'),
  t('Pyramids', 'triangular tomb, hieroglyphs'),
  t('Hindu Mythology', 'ganesha elephant, cosmic dance'),
  t('Shiva', 'third eye, cosmic dancer'),
  t('Hanuman', 'monkey god, flying mountain'),
  t('Kali', 'many arms, fierce protector'),
  t('Chinese Dragon', 'serpent of good luck, cloud chase'),
  t('Phoenix', 'rebirth from ashes, fire wing'),
  t('Monkey King', 'sun wukong, cloud staff'),
  t('Japanese Kitsune', 'fox spirit, nine tails, torii'),
  t('Tengu', 'mountain spirit, long nose'),
  t('Oni', 'demon mask, horns'),
  t('Yokai', 'spirit assembly, folklore creatures'),
  t('Celtic Druids', 'oak grove, mistletoe sickle'),
  t('Banshee', 'wailing spirit, green shroud'),
  t('Leprechaun', 'pot of gold, four leaf clover'),
  t('Thunderbird', 'native spirit, storm wing'),
  t('Wendigo', 'winter starvation, antler skull'),
  t('Moana Legends', 'maui hook, demigod'),
  t('Aboriginal Dreamtime', 'songline, rainbow serpent, dot painting'),
  t('Anansi', 'spider trickster, stories'),
  t('Voodoo', 'veve symbol, loa spirits'),
  t('Baba Yaga', 'chicken leg hut, slavic witch'),
  t('Firebird', 'glowing plumage, slavic tale'),
  t('Genie', 'lamp wish, arabian night'),
  t('Mayan Gods', 'feathered serpent, calendar stone'),
  t('Aztec Gods', 'obsidian blade, sun stone'),
  t('Inca Temples', 'sun god, stonework'),

  // ========== ART MOVEMENTS ==========
  t('Bauhaus', 'primary colors, geometric modernism'),
  t('De Stijl', 'mondrian grid, red blue yellow'),
  t('Cubism', 'picasso angles, fractured form'),
  t('Futurism', 'speed lines, italian modernism'),
  t('Constructivism', 'soviet poster, geometric red'),
  t('Dadaism', 'absurdist collage, anti art'),
  t('Surrealism', 'dream melt, dali clock'),
  t('Abstract Expressionism', 'action drip, pollock splatter'),
  t('Pop Art', 'warhol soup, halftone dot'),
  t('Op Art', 'visual illusion, black and white'),
  t('Minimalism', 'negative space, pure form'),
  t('Conceptual Art', 'idea over object, text art'),
  t('Street Art', 'spray stencil, banksy irony'),
  t('Graffiti Wildstyle', 'tag letters, can nozzle'),
  t('Impressionism', 'plein air, brush flicker, monet garden'),
  t('Post-Impressionism', 'van gogh swirl, cezanne structure'),
  t('Fauvism', 'wild color, matisse'),
  t('Expressionism', 'emotional distortion, scream'),
  t('Romanticism', 'sublime landscape, stormy sea'),
  t('Neoclassicism', 'marble column, civic virtue'),
  t('Ukiyo-e', 'woodblock print, hokusai wave'),
  t('Sumi-e', 'ink wash, zen brush'),
  t('Aboriginal Art', 'dot painting, dreamtime'),
  t('Haida Art', 'pacific northwest, formline'),
  t('Inuit Art', 'soapstone carving, arctic life'),
  t('Islamic Art', 'geometric tessellation, calligraphy'),
  t('Stained Glass Art', 'rose window, light refraction'),

  // ========== PROFESSIONS ==========
  t('Firefighter', 'maltese cross, ladder truck, helmet'),
  t('Paramedic', 'caduceus, ambulance bay'),
  t('Police', 'badge, patrol'),
  t('Doctor', 'caduceus, stethoscope'),
  t('Surgeon', 'scalpel, steady hand'),
  t('Nurse', 'hypocrates, compassionate care'),
  t('Veterinarian', 'paw print stethoscope'),
  t('Lawyer', 'gavel, scales of justice'),
  t('Teacher', 'chalkboard, apple'),
  t('Scientist', 'lab flask, discovery'),
  t('Astronomer', 'telescope, star chart'),
  t('Engineer', 'gear pinion, blueprint'),
  t('Architect', 'drafting compass, tower'),
  t('Carpenter', 'hammer nail, measured cut'),
  t('Electrician', 'lightning bolt, conduit'),
  t('Plumber', 'pipe wrench, copper coil'),
  t('Mechanic', 'torque wrench, oil mark'),
  t('Chef', 'toque hat, knife skill'),
  t('Baker', 'rolling pin, flour apron'),
  t('Butcher', 'cleaver, cuts diagram'),
  t('Farmer', 'pitchfork, barn silo'),
  t('Rancher', 'brand iron, horse lariat'),
  t('Cowboy', 'spur boot, sunset silhouette'),
  t('Fisherman', 'gloucester boat, net cast'),
  t('Logger', 'flannel axe, timber fall'),
  t('Miner', 'pickaxe, canary cage'),
  t('Pilot', 'aviator glasses, wings pin'),
  t('Sailor', 'anchor tattoo, navy stripe'),
  t('Soldier', 'dog tags, silhouette'),
  t('Astronaut', 'helmet reflection, mission patch'),
  t('Chemist', 'beaker, periodic table'),
  t('Biologist', 'petri dish, microscope'),
  t('Geologist', 'rock hammer, strata'),

  // ========== HOLIDAYS & SEASONAL ==========
  t('Halloween', 'jack-o-lantern, ghost shape, bat swarm'),
  t('Christmas', 'tree star, stockings, gingerbread'),
  t('Hanukkah', 'menorah, dreidel, oil miracle'),
  t('New Year', 'fireworks burst, confetti clock'),
  t('Lunar New Year', 'dragon dance, red envelope, firecracker'),
  t('Valentine', 'heart arrow, rose bouquet'),
  t("St. Patrick's Day", 'shamrock, leprechaun hat'),
  t('Cinco de Mayo', 'papel picado, sombrero, mariachi'),
  t('Dia de los Muertos', 'sugar skull, marigold, altar'),
  t('Thanksgiving', 'cornucopia, turkey, harvest'),
  t('Easter', 'egg pattern, bunny, spring bloom'),
  t('Independence Day', 'stars and stripes, liberty, fireworks'),
  t('Oktoberfest', 'beer stein, pretzel, lederhosen'),
  t('Mardi Gras', 'feathered mask, beads, parade float'),
  t('Holi', 'color powder, spring joy'),
  t('Diwali', 'oil lamp, rangoli pattern'),
  t('Eid', 'crescent moon, lantern, celebration'),
  t('Ramadan', 'date palm, prayer beads, crescent'),

  // ========== TECH & DIGITAL ==========
  t('Retro Tech', 'walkman, boom box, cassette'),
  t('80s Aesthetic', 'neon wire, chrome, grid sunset'),
  t('90s Nostalgia', 'floppy disc, tamagotchi, nickelodeon slime'),
  t('Y2K', 'shiny metallic, frosted plastic'),
  t('VHS', 'tracking lines, static, rental sticker'),
  t('CRT Monitor', 'scan lines, glass bulge'),
  t('Pixel Art', '8-bit hero, dithered gradient'),
  t('Glitch Art', 'digital corruption, chromatic shift'),
  t('Circuit Board', 'pcb trace, silicon maze'),
  t('Robot', 'bolted joints, blinking eye'),
  t('Mecha', 'giant cockpit, weaponized limb'),
  t('Cyborg', 'flesh and steel, neural port'),
  t('AI Brain', 'neural network web, synapse'),
  t('Hacker', 'terminal green, hoodie, matrix'),
  t('Arcade', 'cabinet stick, joystick fight'),
  t('Pinball', 'flipper, bumper, plunger'),
  t('Neon Sign', 'bent glass, cursive glow'),

  // ========== ABSTRACT EMOTIONS ==========
  t('Freedom', 'broken chain, open sky, bird flight'),
  t('Rebellion', 'raised fist, torn flag, protest'),
  t('Peace', 'dove olive branch, open palm'),
  t('Love', 'linked hands, heart, embrace'),
  t('Nostalgia', 'faded polaroid, childhood memory'),
  t('Wanderlust', 'suitcase label, compass, horizon'),
  t('Melancholy', 'rainy window, empty chair'),
  t('Zen', 'stacked stones, raked sand, stillness'),
  t('Mindfulness', 'lotus, breath, present moment'),
  t('Chaos', 'fractal storm, tangled lines'),
  t('Order', 'grid perfect, mandelbrot'),
  t('Dreams', 'floating form, soft mist, subconscious'),
  t('Time', 'hourglass, clockwork, flowing river'),
  t('Memory', 'sepia photo, fragmented image'),
  t('Courage', 'lion roar, warrior stance'),
  t('Wisdom', 'old tree, owl, ancient text'),

  // ========== TEXTURES & MATERIALS ==========
  t('Marble', 'veined slab, cool polish'),
  t('Wood Grain', 'ring pattern, oak knot'),
  t('Leather', 'tooled pattern, stitched seam'),
  t('Denim', 'warp weft, copper rivet'),
  t('Tweed', 'houndstooth weave, countryside'),
  t('Velvet', 'crushed nap, jewel tone'),
  t('Silk', 'flowing drape, sheen'),
  t('Rope', 'braided twist, knot detail'),
  t('Chain', 'interlinked, iron forged'),
  t('Lace', 'openwork pattern, bridal'),
  t('Stone Wall', 'mortared block, mossy'),
  t('Brick', 'weathered red, mason line'),
  t('Concrete', 'brutalist form, poured texture'),
  t('Rust', 'oxidized patina, weathered steel'),
  t('Barbed Wire', 'fence row, coiled menace'),
  t('Bone', 'skeletal structure, fossil'),

  // ========== PLANTS & FLOWERS ==========
  t('Rose', 'petal spiral, thorny stem'),
  t('Tulip', 'cupped petal, spring field'),
  t('Peony', 'full bloom, ruffled layers'),
  t('Lily', 'stargazer, funnel form'),
  t('Orchid', 'exotic curve, tropical rare'),
  t('Sunflower', 'seed spiral, golden petal'),
  t('Lotus', 'sacred bloom, mud purity'),
  t('Poppy', 'red field, remembrance'),
  t('Hibiscus', 'tropical trumpet'),
  t('Cactus', 'spine silhouette, desert survivor'),
  t('Bamboo', 'jointed stalk, green serenity'),
  t('Bonsai', 'miniature tree, zen training'),
  t('Palm Tree', 'frond sway, tropical'),
  t('Oak Tree', 'majestic branch, acorn'),
  t('Willow', 'weeping branch, riverside'),
  t('Cherry Blossom', 'sakura petal, ephemeral bloom'),
  t('Maple Leaf', 'autumn flame, canada'),
  t('Ginkgo', 'fan leaf, ancient tree'),
  t('Fern', 'unfurling fiddlehead, spore pattern'),
  t('Moss', 'velvet green, forest floor'),
  t('Succulent', 'geometric rosette, arid garden'),
  t('Aloe', 'spiky gel leaf'),
  t('Eucalyptus', 'silver leaf, aromatic branch'),
  t('Monstera', 'swiss cheese leaf, jungle'),
  t('Mushroom', 'fairy ring, spotted cap'),
  t('Fly Agaric', 'red white mushroom, folklore'),
  t('Wheat', 'amber grain, field harvest'),
  t('Corn', 'husked ear, silks'),

  // ========== FASHION & STYLE ==========
  t('Haute Couture', 'runway gown, atelier'),
  t('Streetwear', 'hoodie, sneakers, urban'),
  t('Vintage Denim', 'selvedge edge, worn knee'),
  t('Leather Jacket', 'biker studs, vintage patina'),
  t('Tweed Suit', 'british countryside'),
  t('Pinstripe', 'vertical line suit, gangster'),
  t('Paisley', 'teardrop ornament, bohemian'),
  t('Plaid', 'tartan cross, highland'),
  t('Herringbone', 'zigzag weave, tailor'),
  t('Houndstooth', 'broken check, chanel'),
  t('Polka Dot', 'even circle, fifties'),
  t('Argyle', 'diamond check, golf sweater'),
  t('Camouflage', 'blob pattern, tactical'),
  t('Digital Camo', 'pixelated stealth'),

  // ========== WEATHER & ATMOSPHERE ==========
  t('Thunderstorm', 'lightning fork, rain sheet'),
  t('Tornado', 'funnel cloud, midwest power'),
  t('Hurricane', 'spiral eye, palm bend'),
  t('Blizzard', 'whiteout snow, howl wind'),
  t('Sandstorm', 'ochre cloud, dune erase'),
  t('Monsoon', 'heavy rain, banana leaf'),
  t('Fog', 'pea soup, muffled world'),
  t('Mist', 'mountain valley, silver veil'),
  t('Dew', 'spider web diamond, dawn'),

  // ========== ANATOMY & SCIENCE ==========
  t('Anatomy Sketch', 'leonardo cross section, muscle study'),
  t('Skeleton', 'bone structure, articulated'),
  t('Skull', 'memento mori, crystal detail'),
  t('Heart Anatomy', 'chambered organ, vessel tree'),
  t('Brain', 'neural fold, gray matter'),
  t('DNA', 'double helix, base pair'),
  t('Cell', 'organelle, membrane'),
  t('Atom', 'electron orbit, nucleus'),
  t('Molecule', 'bonded sphere, hexagonal'),
  t('Fractal', 'self similar, mandelbrot'),
  t('Fibonacci', 'golden spiral, nautilus'),
  t('Sacred Spiral', 'phi ratio, growth pattern'),

  // ========== TRAVEL & EXPLORATION ==========
  t('Vintage Travel Poster', 'retro tourism, grand vista'),
  t('Road Trip', 'highway sign, open desert'),
  t('Route 66', 'mother road, neon motel'),
  t('Pacific Coast Highway', 'cliff drive, convertible'),
  t('Trans-Siberian', 'railway, vast steppe'),
  t('Silk Road', 'camel caravan, oasis'),
  t('Appalachian Trail', 'white blaze, thru-hike'),
  t('Everest Expedition', 'base camp, yak'),
  t('Safari', 'land rover, zebra crossing'),
  t('Amazon Expedition', 'dugout canoe, emerald green'),
  t('Arctic Expedition', 'dog sled, ice floe'),
  t('Space Exploration', 'lunar footprint, rover'),

  // ========== INDUSTRIAL & URBAN ==========
  t('Industrial', 'factory stack, rivet steel'),
  t('Warehouse', 'corrugated metal, loading dock'),
  t('Railway', 'locomotive, track vanishing'),
  t('Shipyard', 'crane gantry, hull'),
  t('Oil Rig', 'offshore platform, flame stack'),
  t('Refinery', 'twisted pipes, cracking tower'),
  t('Skyscraper', 'steel skeleton, reflective glass'),
  t('Bridge', 'suspension cable, arch'),
  t('Urban Decay', 'abandoned factory, broken window'),
  t('Graffiti Alley', 'back street canvas, tag layer'),
  t('Subway', 'tunnel rush, metro tile'),
  t('Docks', 'container color, gantry'),

  // ========== WESTERN & FRONTIER ==========
  t('Old West', 'wanted poster, saloon door, dust'),
  t('Gunslinger', 'leather holster, tumbleweed'),
  t('Native American', 'feather headdress, dream catcher, sacred'),
  t('Spirit Animal', 'totem, guide, vision quest'),
  t('Navajo', 'diamond weave, red rock loom'),
  t('Apache', 'desert warrior, medicine wheel'),
  t('Gold Rush', 'pan sluice, claim stake'),
  t('Homestead', 'sod house, prairie'),
  t('Stagecoach', 'dusty road, horse team'),
  t('Train Robbery', 'bandana mask, iron horse'),

  // ========== GOTHIC & DARK ==========
  t('Haunted House', 'creaking porch, flickering candle'),
  t('Graveyard', 'weathered stone, raven perch'),
  t('Skull & Crossbones', 'pirate warning, toxic'),
  t('Grim Reaper', 'scythe silhouette, hooded'),
  t('Crypt', 'stone sarcophagus, torch'),
  t('Vampire', 'gothic castle, bat transform'),
  t('Werewolf', 'full moon howl, forest'),
  t('Zombie', 'decaying, outstretched hand'),
  t('Ghost', 'ethereal wisp, ectoplasm'),
  t('Witch', 'cauldron, broomstick, familiar'),
  t('Ouija', 'planchette, spirit board'),
  t('Pentagram', 'five-point star, occult'),
  t('Tarot Card', 'illustrated divination'),
  t('Skeleton Key', 'rust lock, hidden door'),

  // ========== WHIMSICAL & FANTASY ==========
  t('Dragon', 'scaled wing, fire breath, hoard'),
  t('Unicorn', 'spiral horn, rainbow mane'),
  t('Mermaid', 'scaled tail, ocean song'),
  t('Fairy', 'gossamer wing, toadstool'),
  t('Gnome', 'pointed hat, garden'),
  t('Elf', 'pointed ear, bow, forest'),
  t('Dwarf', 'axe beard, mountain'),
  t('Wizard', 'staff robe, spell'),
  t('Castle', 'turret flag, drawbridge'),
  t('Knight', 'plate armor, heraldic shield'),
  t('Medieval Tavern', 'wooden beams, hearth'),
  t('Enchanted Forest', 'glowing mushroom, misty path'),
  t('Crystal Ball', 'scrying orb, swirling mist'),
  t('Magic Wand', 'starburst tip, incantation'),
  t('Spell Book', 'aged tome, mystical rune'),

  // ========== CANNABIS & SMOKE CULTURE ==========
  t('Cannabis Leaf', 'seven-point leaf, green bloom'),
  t('Hemp Rope', 'natural twist, woven'),
  t('Smoke Plume', 'curling wisp, cloud drift'),
  t('Incense', 'stick spiral, ceremonial'),
  t('Hookah', 'persian water pipe, ornate'),
  t('Peace Pipe', 'calumet, native ritual'),
  t('Bamboo Pipe', 'artisan craft, natural'),
  t('Rasta', 'red gold green, lion judah'),
  t('Dub Reggae', 'smoky bass, kingston'),
  t('Haze', 'thick cloud, hazy sunset'),

  // ========== ICONS & SYMBOLS ==========
  t('Yin Yang', 'dual balance, flowing curve'),
  t('Ankh', 'egyptian eternal life'),
  t('Ouroboros', 'snake eating tail, eternity'),
  t('Tree of Life', 'roots and branches, connection'),
  t('Eye of Providence', 'all seeing, triangle'),
  t('Fleur-de-lis', 'royal lily, french'),
  t('Triquetra', 'trinity knot, celtic'),
  t('Hamsa', 'protective hand, evil eye'),
  t('Om Symbol', 'hindu primordial sound'),
  t('Dharma Wheel', 'eight spokes, buddhist'),
  t('Infinity', 'lemniscate loop, endless'),
  t('Atom Symbol', 'electron path, science'),
  t('Peace Sign', 'sixties anti-war'),
  t('Anchor', 'nautical hope, fouled'),
  t('Compass Rose', 'four points, wind directions'),
  t('Arrow', 'direction, hunt, sagittarius'),
  t('Keys', 'skeleton key, unlocking'),
  t('Crown', 'royal jewels, sovereign'),
  t('Scepter', 'rule of power'),
  t('Trident', 'three prong, neptune'),
  t('Sword', 'blade hilt, courage'),
  t('Shield', 'coat of arms, defense'),

  // ========== RANDOM & ABSTRACT ==========
  t('Lightning', 'jagged bolt, electric storm'),
  t('Fire', 'dancing flames, campfire'),
  t('Water', 'rippling surface, droplet'),
  t('Earth Element', 'mountain, soil, grounded'),
  t('Air Element', 'wind flow, cloud dance'),
  t('Eclipse', 'sun moon corona, celestial event'),
  t('Constellation', 'dot connection, star map'),
  t('Big Dipper', 'ursa major, northern sky'),
  t('Orion', 'hunter belt, winter sky'),
  t('Zodiac', 'twelve signs, astrological'),
  t('Aries', 'ram horns, fire sign'),
  t('Taurus', 'bull head, earth sign'),
  t('Gemini', 'twin figures, air sign'),
  t('Cancer', 'crab shell, water sign'),
  t('Leo', 'lion mane, fire sign'),
  t('Virgo', 'maiden wheat, earth sign'),
  t('Libra', 'balance scale, air sign'),
  t('Scorpio', 'scorpion sting, water sign'),
  t('Sagittarius', 'archer centaur, fire sign'),
  t('Capricorn', 'sea goat, earth sign'),
  t('Aquarius', 'water bearer, air sign'),
  t('Pisces', 'two fish, water sign'),

  // ========== CULTURAL ICONS ==========
  t('Kabuki', 'painted face, dramatic pose'),
  t('Noh Theatre', 'carved mask, slow pageant'),
  t('Chinese Opera', 'elaborate costume, painted face'),
  t('Indian Kathak', 'dancer twirl, ghungroo bells'),
  t('Spanish Bullfighter', 'cape flourish, matador suit'),
  t('Brazilian Carnival', 'feathered samba, drum line'),
  t('Venetian Carnival', 'bauta mask, silk cape'),
  t('Greek Bouzouki', 'folk string, island taverna'),
  t('Balinese Dance', 'finger curl, offering'),
  t('Haka', 'maori war chant, tongue out'),

  // ========== RANDOM VIBES ==========
  t('Film Noir', 'venetian blind shadow, trench coat'),
  t('Midcentury Modern', 'atomic age, starburst'),
  t('Tiki Culture', 'polynesian bar, rum cocktail'),
  t('Roaring Twenties', 'flapper, art deco jazz'),
  t('Disco 70s', 'dancefloor fever, glitter ball'),
  t('Punk 80s', 'mohawk, safety pin, anarchy'),
  t('Rave Culture', 'glowstick, warehouse party'),
  t('Goth Subculture', 'black lace, pale makeup'),
  t('Emo Culture', 'side swept bangs, striped sleeve'),
  t('Surf Culture', 'woody wagon, longboard'),
  t('Skater Culture', 'palace ledges, kickflip'),
  t('Hip Hop Culture', 'boom box, breakdance, tag'),
  t('Goth Victorian', 'mourning lace, cameo'),
  t('Dark Academia', 'oxford library, leather tome'),
  t('Cottagecore', 'meadow picnic, baking bread'),
  t('Farmhouse', 'barnwood, enamel pitcher'),
  t('Coastal Grandmother', 'linen shirt, beach house'),
  t('Balkan Folk', 'embroidered tunic, wooden dance'),

  // ========== RANDOM OBJECTS / TOOLS ==========
  t('Vintage Camera', 'leather bellows, brass lens'),
  t('Typewriter', 'key letters, ribbon, letterpress feel'),
  t('Vinyl Record', 'grooved disc, record sleeve'),
  t('Cassette Tape', 'magnetic ribbon, mixtape'),
  t('Polaroid', 'instant photo, white border'),
  t('Pocket Watch', 'fob chain, roman numeral'),
  t('Compass', 'magnetic needle, explorer'),
  t('Sextant', 'celestial navigation, brass arc'),
  t('Hourglass', 'sand trickle, passage of time'),
  t('Magnifying Glass', 'sherlock detail, discovery'),
  t('Quill Pen', 'ink well, feathered nib'),
  t('Lantern', 'old oil glow, storm light'),
  t('Sundial', 'shadow hour, garden marker'),
  t('Telescope', 'brass tube, celestial eye'),
  t('Microscope', 'precision lens, slide'),
  t('Globe', 'spinning world, cartography'),
  t('Atlas Map', 'old cartography, compass rose'),
  t('Astrolabe', 'antique astronomy, brass dial'),
  t('Abacus', 'beaded calculator, wooden frame'),

  // ========== MISC CULTURE ==========
  t('Speakeasy', 'prohibition era, hidden bar'),
  t('Film Festival', 'red carpet, spotlight'),
  t('Concert Poster', 'band list, venue typography'),
  t('Skatepark', 'bowl curve, coping grind'),
  t('Barber Shop', 'pole spin, straight razor'),
  t('Tattoo Studio', 'flash sheet, needle, traditional'),
  t('Neo-traditional Tattoo', 'bold line, saturated color'),
  t('Blackwork Tattoo', 'all black, geometric'),
  t('Biomechanical Tattoo', 'gears in flesh'),
  t('Ornamental Tattoo', 'mandala shoulder, ornament'),
  t('Japanese Tattoo', 'irezumi koi, waves'),
  t('Old School Tattoo', 'sailor jerry, bold pin-up'),

  // ========== SMOKING-RELATED THEMES (fits your brand) ==========
  t('High Times Vibe', 'retro 70s weed, psychedelic cannabis'),
  t('Stoner Comedy', 'lazy laughter, cheech chong'),
  t('Rolling Tray', 'brass grinder, paper'),
  t('Bongsmith Lore', 'borosilicate beauty, water percolator'),
  t('420 Nostalgia', 'time honored ritual'),
  t('Hemp Fields', 'green stalks swaying'),
  t('Sunset Session', 'golden hour, slow exhale'),
  t('Mountain Session', 'alpine overlook, chill'),
  t('Beach Session', 'ocean horizon, sandy toes'),
  t('Couch Lock', 'velvet sofa, movie glow'),
  t('Desert Festival', 'burning man, playa dust'),
  t('Forest Campout', 'tent flap, lantern'),
  t('Lake House', 'dock boards, canoe'),

  // ========== LIFESTYLE MOODS ==========
  t('Slow Living', 'morning coffee, reading nook'),
  t('Minimalist Tokyo Apartment', 'tatami, clean line'),
  t('Rustic Cabin', 'log wall, iron stove'),
  t('Parisian Apartment', 'herringbone floor, balcony rail'),
  t('Mediterranean Villa', 'olive tree, terracotta pot'),
  t('Scandinavian Home', 'light wood, wool throw'),
  t('Japanese Onsen', 'cedar tub, steam rise'),
  t('Spanish Patio', 'cobalt tile, fountain'),
  t('Moroccan Riad', 'lantern courtyard, zellige'),
  t('Coastal Cottage', 'whitewash, nautical'),
  t('Urban Loft', 'exposed brick, steel beam'),
  t('Treehouse', 'canopy perch, rope ladder'),

  // ========== SEASON & TIME OF DAY ==========
  t('Spring Awakening', 'cherry bud, rainy green'),
  t('Summer Heat', 'sunflowers, cicada song'),
  t('Autumn Leaves', 'maple fall, pumpkin spice'),
  t('Winter Quiet', 'bare birch, snow silence'),
  t('Golden Hour', 'warm slant light, dust mote'),
  t('Twilight', 'violet sky, first stars'),
  t('Midnight', 'indigo black, witching hour'),
  t('Dawn', 'pink horizon, mist rise'),

  // ========== FILM & POP CULTURE VIBES ==========
  t('Wes Anderson', 'symmetrical composition, pastel palette'),
  t('David Lynch', 'surreal diner, red curtain'),
  t('Tarantino', 'pulp violence, diner dialogue'),
  t('Coen Brothers', 'dark comedy, snowy midwest'),
  t('Kubrick', 'symmetrical hallway, stare'),
  t('Studio Ghibli', 'floating castle, forest spirit'),
  t('Blade Runner', 'neon rain, flying car'),
  t('Mad Max', 'dusty wasteland, rusted warpaint'),
  t('Star Wars', 'galaxy far away, lightsaber glow'),
  t('Spaghetti Western', 'sergio leone squint, duel'),
  t('Giallo Horror', 'italian mystery, black gloves'),
  t('80s Action', 'arnold muscle, aviators'),

  // ========== MORE HOBBIES & LIFESTYLE ==========
  t('Bass Fishing', 'lure tackle, largemouth bass, tournament'),
  t('Crappie Fishing', 'panfish stringer, brush pile'),
  t('Trout Fishing', 'mountain stream, rainbow flash'),
  t('Saltwater Fishing', 'charter boat, gaff hook, mahi'),
  t('Duck Hunting', 'decoy spread, wader boots, retriever'),
  t('Bow Hunting', 'tree stand, compound bow, rut'),
  t('Dog Training', 'whistle, clicker, loyal retriever'),
  t('Cat Lover', 'whisker profile, cozy perch'),
  t('Horse Rescue', 'rescued stallion, open pasture'),
  t('Bird Hunting', 'pointer dog, pheasant flush'),
  t('Trap Shooting', 'clay pigeon burst, shotgun'),
  t('Skeet', 'shooting station, lead and swing'),
  t('Paintball', 'splatter burst, camo field'),
  t('Disc Golf', 'chain basket, putter flick'),
  t('Pickleball', 'paddle, whiffle ball court'),

  // ========== MORE WORLD CULTURES ==========
  t('Irish Pub', 'cozy snug, pint Guinness, trad music'),
  t('Scottish Highlands', 'kilt tartan, heather moor'),
  t('Welsh Coast', 'dragon flag, slate hill'),
  t('Bavarian', 'dirndl, cuckoo clock, alpine'),
  t('Basque Country', 'txalaparta, cave painting'),
  t('Catalan', 'fiery flag, casteller tower'),
  t('Andalusian', 'flamenco, white village'),
  t('Tuscan', 'cypress lane, vineyard hill'),
  t('Provence', 'lavender field, stone farmhouse'),
  t('Bohemian', 'crystal chandelier, beer hall'),

  // ========== MORE OUTDOOR / MARINE ==========
  t('Lake Life', 'dock boards, cooler, pontoon'),
  t('River Life', 'tubing down, gravel bar'),
  t('Marina Life', 'slip finger, outrigger rod'),
  t('Yacht Club', 'burgee flag, regatta, blazer'),
  t('Fly Tying', 'feathered hook, vise, craft'),
  t('Kite Flying', 'beach wind, diamond kite'),
  t('Bonfire Night', 'driftwood crackle, marshmallow'),
  t('Star Party', 'amateur astronomers, big scope'),

  // ========== MORE MUSIC VIBES ==========
  t('Sea Shanty', 'pirate chant, rope rhythm'),
  t('Cowboy Ballad', 'campfire, lonesome whistle'),
  t('Gospel Choir', 'stained glass, raised voice'),
  t('Appalachian Folk', 'mountain banjo, porch session'),
  t('Cajun Zydeco', 'accordion, bayou fiddle'),
  t('Tex-Mex', 'conjunto accordion, border'),
];
