import { Concept, SpecTemplate, User } from './types';

export const sampleUsers: User[] = [
  { id: 'u1', name: 'Alex Rivera', role: 'admin', avatar: 'AR' },
  { id: 'u2', name: 'Jordan Chen', role: 'designer', avatar: 'JC' },
  { id: 'u3', name: 'Sam Patel', role: 'reviewer', avatar: 'SP' },
];

export const sampleConcepts: Concept[] = [
  {
    id: 'c1',
    name: 'Sacred Geometry V1',
    collection: 'Geometry Series',
    status: 'approved',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-01T14:30:00Z',
    designer: 'Alex Rivera',
    tags: ['geometric', 'premium', 'bestseller'],
    description: 'Interlocking sacred geometry patterns with flower of life centerpiece on base and mandala wrap on coil.',
    intendedAudience: 'Premium collectors, spiritual aesthetic',
    manufacturingNotes: 'Medium complexity. Line thickness must be 0.3mm minimum for clean etch.',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Sacred Geometry',
      designTheme: 'Spiritual / Mathematical',
      patternDensity: 'high',
      laserComplexity: 4,
      estimatedEtchingTime: '12 min',
      surfaceCoverage: 75,
      lineThickness: '0.3mm',
      bwContrastGuidance: 'High contrast, clean white space between lines',
      symmetryRequirement: 'symmetrical',
      coordinationMode: 'exact_match',
      productionFeasibility: 4,
      riskNotes: 'Fine detail in flower of life center may fill in at high speed',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: 'Full wraparound mandala' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: 'Flower of life centered' },
    priority: 'high',
    lifecycleType: 'evergreen',
    versions: [
      { id: 'v1', conceptId: 'c1', versionNumber: 1, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Initial concept sketch', createdAt: '2026-03-15T10:00:00Z' },
      { id: 'v2', conceptId: 'c1', versionNumber: 2, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Refined line weights, added border pattern', createdAt: '2026-03-20T16:00:00Z' },
    ],
    comments: [
      { id: 'cm1', conceptId: 'c1', userId: 'u2', userName: 'Jordan Chen', text: 'Love the symmetry. Maybe thicken the outer ring lines?', createdAt: '2026-03-16T09:00:00Z' },
      { id: 'cm2', conceptId: 'c1', userId: 'u3', userName: 'Sam Patel', text: 'Approved. Ready for test etch.', createdAt: '2026-04-01T14:30:00Z' },
    ],
    approvalLogs: [
      { id: 'a1', conceptId: 'c1', userId: 'u3', userName: 'Sam Patel', action: 'approved', notes: 'Clean design, production ready', createdAt: '2026-04-01T14:30:00Z' },
    ],
    aiGenerations: [],
  },
  {
    id: 'c2',
    name: 'Serpent Coil Wrap',
    collection: 'Creature Series',
    status: 'in_review',
    createdAt: '2026-03-25T08:00:00Z',
    updatedAt: '2026-04-03T11:00:00Z',
    designer: 'Jordan Chen',
    tags: ['snake', 'creature', 'detailed', 'wraparound'],
    description: 'A coiling serpent that wraps around the coil piece with scales and a complementary base featuring a coiled snake viewed from above.',
    intendedAudience: 'Edgy, tattoo culture, collector appeal',
    manufacturingNotes: 'Scale detail is very fine. May need simplification pass.',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Creature Illustration',
      designTheme: 'Serpent / Snake',
      patternDensity: 'very_high',
      laserComplexity: 5,
      estimatedEtchingTime: '18 min',
      surfaceCoverage: 85,
      lineThickness: '0.25mm',
      bwContrastGuidance: 'Heavy black areas for body, fine lines for scales',
      symmetryRequirement: 'wraparound',
      coordinationMode: 'thematic',
      productionFeasibility: 3,
      riskNotes: 'Scale detail may be too fine. Individual scales under 0.5mm may merge.',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: 'Snake wraps full circumference' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: 'Top-down coiled snake view' },
    priority: 'high',
    lifecycleType: 'evergreen',
    versions: [
      { id: 'v3', conceptId: 'c2', versionNumber: 1, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Initial serpent concept', createdAt: '2026-03-25T08:00:00Z' },
    ],
    comments: [
      { id: 'cm3', conceptId: 'c2', userId: 'u1', userName: 'Alex Rivera', text: 'Incredible concept but the scales need to be bigger for production.', createdAt: '2026-03-28T10:00:00Z' },
    ],
    approvalLogs: [],
    aiGenerations: [],
  },
  {
    id: 'c3',
    name: 'Smoke Drift Abstract',
    collection: 'Abstract Series',
    status: 'ideation',
    createdAt: '2026-04-02T15:00:00Z',
    updatedAt: '2026-04-02T15:00:00Z',
    designer: 'Alex Rivera',
    tags: ['abstract', 'smoke', 'flowing', 'minimal'],
    description: 'Flowing smoke wisps that drift across the coil and base in a coordinated but organic pattern.',
    intendedAudience: 'Mainstream, clean aesthetic',
    manufacturingNotes: '',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Abstract Smoke',
      designTheme: 'Organic Flow',
      patternDensity: 'medium',
      laserComplexity: 2,
      estimatedEtchingTime: '8 min',
      surfaceCoverage: 40,
      lineThickness: '0.5mm',
      bwContrastGuidance: 'Soft gradients replaced with stipple/line work',
      symmetryRequirement: 'none',
      coordinationMode: 'loose',
      productionFeasibility: 5,
      riskNotes: 'Very production-friendly design',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: '' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: '' },
    priority: 'medium',
    lifecycleType: 'evergreen',
    versions: [],
    comments: [],
    approvalLogs: [],
    aiGenerations: [],
  },
  {
    id: 'c4',
    name: '4th of July Eagle',
    collection: 'Patriotic Series',
    status: 'ideation',
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-05T09:00:00Z',
    designer: 'Jordan Chen',
    tags: ['patriotic', 'eagle', 'seasonal', 'bold'],
    description: 'Bold eagle design with stars and stripes elements for Independence Day limited drop.',
    intendedAudience: 'Patriotic market, holiday buyers',
    manufacturingNotes: 'Need by June 15 for July 4th sales',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Patriotic Illustration',
      designTheme: 'American Eagle',
      patternDensity: 'high',
      laserComplexity: 4,
      estimatedEtchingTime: '14 min',
      surfaceCoverage: 70,
      lineThickness: '0.35mm',
      bwContrastGuidance: 'Bold contrast, heavy fills for impact',
      symmetryRequirement: 'none',
      coordinationMode: 'thematic',
      productionFeasibility: 4,
      riskNotes: 'Star details on stripes need adequate spacing',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: 'Stars and stripes wrap' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: 'Eagle head centered' },
    priority: 'urgent',
    lifecycleType: 'seasonal',
    versions: [],
    comments: [],
    approvalLogs: [],
    aiGenerations: [],
  },
  {
    id: 'c5',
    name: 'Luxury Gold Leaf',
    collection: 'Premium Collection',
    status: 'ready_for_manufacturing',
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-03-28T16:00:00Z',
    designer: 'Alex Rivera',
    tags: ['luxury', 'premium', 'ornate', 'gold'],
    description: 'Ornate baroque-style leaf scrollwork with fine filigree details. Premium positioning.',
    intendedAudience: 'High-end buyers, luxury gift market',
    manufacturingNotes: 'Test etch completed. Use slow speed setting for filigree.',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Baroque Ornamental',
      designTheme: 'Luxury Filigree',
      patternDensity: 'very_high',
      laserComplexity: 5,
      estimatedEtchingTime: '20 min',
      surfaceCoverage: 80,
      lineThickness: '0.2mm',
      bwContrastGuidance: 'Maximum contrast, intricate fill patterns',
      symmetryRequirement: 'symmetrical',
      coordinationMode: 'exact_match',
      productionFeasibility: 3,
      riskNotes: 'Filigree can clog at high speeds. Requires slow pass.',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: 'Symmetrical scroll on both sides' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: 'Centered medallion with scrollwork border' },
    priority: 'high',
    lifecycleType: 'evergreen',
    versions: [
      { id: 'v4', conceptId: 'c5', versionNumber: 1, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Initial baroque concept', createdAt: '2026-02-10T12:00:00Z' },
      { id: 'v5', conceptId: 'c5', versionNumber: 2, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Simplified filigree for production', createdAt: '2026-03-01T10:00:00Z' },
      { id: 'v6', conceptId: 'c5', versionNumber: 3, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Final production version', createdAt: '2026-03-20T14:00:00Z' },
    ],
    comments: [],
    approvalLogs: [
      { id: 'a2', conceptId: 'c5', userId: 'u1', userName: 'Alex Rivera', action: 'approved', notes: 'Test etch looks great', createdAt: '2026-03-28T16:00:00Z' },
    ],
    aiGenerations: [],
  },
  {
    id: 'c6',
    name: 'Hex Grid Minimal',
    collection: 'Geometry Series',
    status: 'manufactured',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
    designer: 'Sam Patel',
    tags: ['geometric', 'minimal', 'clean', 'hex'],
    description: 'Clean hexagonal grid pattern with subtle depth illusion. Very production-friendly.',
    intendedAudience: 'Mainstream, modern aesthetic',
    manufacturingNotes: 'Batch 1 complete. Clean etch at standard speed.',
    coilImageUrl: '',
    baseImageUrl: '',
    combinedImageUrl: '',
    specs: {
      designStyleName: 'Geometric Minimal',
      designTheme: 'Hexagonal Grid',
      patternDensity: 'medium',
      laserComplexity: 2,
      estimatedEtchingTime: '6 min',
      surfaceCoverage: 55,
      lineThickness: '0.4mm',
      bwContrastGuidance: 'Clean lines, even spacing',
      symmetryRequirement: 'wraparound',
      coordinationMode: 'exact_match',
      productionFeasibility: 5,
      riskNotes: 'None. Very clean design.',
    },
    coilSpecs: { dimensions: '45mm x 120mm wrap', printableArea: '42mm x 115mm', notes: 'Seamless hex wrap' },
    baseSpecs: { dimensions: '65mm diameter circle', printableArea: '60mm diameter', notes: 'Hex grid with center focal hex' },
    priority: 'medium',
    lifecycleType: 'evergreen',
    versions: [
      { id: 'v7', conceptId: 'c6', versionNumber: 1, coilImageUrl: '', baseImageUrl: '', combinedImageUrl: '', notes: 'Final production version', createdAt: '2026-01-20T10:00:00Z' },
    ],
    comments: [],
    approvalLogs: [
      { id: 'a3', conceptId: 'c6', userId: 'u1', userName: 'Alex Rivera', action: 'approved', notes: 'Ship it', createdAt: '2026-02-15T12:00:00Z' },
    ],
    manufacturingRecord: {
      conceptId: 'c6',
      machineReadyNotes: 'Standard settings, no adjustments needed',
      targetMaterial: 'Borosilicate glass',
      etchingSettings: 'Speed: 300mm/s, Power: 45%, Freq: 20kHz',
      estimatedProductionTime: '6 min per unit',
      batchName: 'HEX-BATCH-001',
      dateSentToProduction: '2026-02-20T08:00:00Z',
      dateManufactured: '2026-03-15T09:00:00Z',
      quantityProduced: 200,
      qcNotes: 'All units passed. Clean etch across batch.',
    },
    aiGenerations: [],
  },
];

export const sampleTemplates: SpecTemplate[] = [
  {
    id: 't1',
    name: 'Geometric',
    category: 'Pattern',
    description: 'Clean geometric patterns with mathematical precision',
    specs: { designStyleName: 'Geometric', patternDensity: 'medium', laserComplexity: 3, symmetryRequirement: 'symmetrical', productionFeasibility: 4 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't2',
    name: 'Floral',
    category: 'Organic',
    description: 'Nature-inspired floral and botanical designs',
    specs: { designStyleName: 'Floral', patternDensity: 'high', laserComplexity: 4, symmetryRequirement: 'none', productionFeasibility: 3 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't3',
    name: 'Abstract Smoke',
    category: 'Abstract',
    description: 'Flowing organic smoke and vapor patterns',
    specs: { designStyleName: 'Abstract Smoke', patternDensity: 'low', laserComplexity: 2, symmetryRequirement: 'none', productionFeasibility: 5 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't4',
    name: 'Snake / Creature',
    category: 'Illustration',
    description: 'Detailed creature illustrations that wrap around surfaces',
    specs: { designStyleName: 'Creature Illustration', patternDensity: 'very_high', laserComplexity: 5, symmetryRequirement: 'wraparound', productionFeasibility: 3 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't5',
    name: 'Patriotic',
    category: 'Themed',
    description: 'American patriotic imagery and symbols',
    specs: { designStyleName: 'Patriotic', patternDensity: 'high', laserComplexity: 4, symmetryRequirement: 'none', productionFeasibility: 4 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't6',
    name: 'Luxury / Premium',
    category: 'Premium',
    description: 'Ornate, baroque-inspired premium designs',
    specs: { designStyleName: 'Luxury Ornamental', patternDensity: 'very_high', laserComplexity: 5, symmetryRequirement: 'symmetrical', productionFeasibility: 2 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't7',
    name: 'Limited Drop',
    category: 'Special',
    description: 'Exclusive limited edition designs with unique elements',
    specs: { designStyleName: 'Limited Edition', patternDensity: 'high', laserComplexity: 4, symmetryRequirement: 'none', productionFeasibility: 3 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
  {
    id: 't8',
    name: 'Holiday / Seasonal',
    category: 'Seasonal',
    description: 'Holiday-themed seasonal designs for limited runs',
    specs: { designStyleName: 'Seasonal', patternDensity: 'medium', laserComplexity: 3, symmetryRequirement: 'none', productionFeasibility: 4 },
    coilSpecs: { dimensions: '45mm x 120mm wrap' },
    baseSpecs: { dimensions: '65mm diameter circle' },
  },
];
